[project]
name = "bluesky-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Seth", email = "wsethgreen@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx2>=2.13.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
bluesky-bot = "bluesky_bot:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
