"""Added initial tables

Revision ID: a65a58a385bb
Revises:
Create Date: 2026-10-04 10:31:47.681326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a65a58a385bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("game_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("team", sa.String(length=10), nullable=False),
        sa.Column("game_state", sa.String(length=20), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index(op.f("ix_games_date"), "games", ["date"], unique=False)
    op.create_index(op.f("ix_games_team"), "games", ["team"], unique=False)
    op.create_table(
        "players",
        sa.Column("player_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "cached_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("team", sa.String(length=10), nullable=False),
        sa.Column(
            "posted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("bsky_uri", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.game_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index(op.f("ix_posts_game_id"), "posts", ["game_id"], unique=False)
    op.create_index(op.f("ix_posts_posted"), "posts", ["posted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_posted"), table_name="posts")
    op.drop_index(op.f("ix_posts_game_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_table("players")
    op.drop_index(op.f("ix_games_team"), table_name="games")
    op.drop_index(op.f("ix_games_date"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
