"""Added initial tables

Revision ID: be7235321067
Revises:
Create Date: 2026-10-04 17:26:16.782098

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be7235321067"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("player_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("team_full_name", sa.String(length=100), nullable=False),
        sa.Column("current_team_id", sa.Integer(), nullable=True),
        sa.Column("current_team_abbrev", sa.String(length=10), nullable=True),
        sa.Column("sweater_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=5), nullable=True),
        sa.Column("headshot", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("plus_minus", sa.Integer(), nullable=False),
        sa.Column("power_play_goals", sa.Integer(), nullable=False),
        sa.Column("power_play_points", sa.Integer(), nullable=False),
        sa.Column("shorthanded_goals", sa.Integer(), nullable=False),
        sa.Column("shorthanded_points", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_index(
        op.f("ix_players_current_team_abbrev"),
        "players",
        ["current_team_abbrev"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_current_team_id"), "players", ["current_team_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("franchise_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("raw_tri_code", sa.String(length=10), nullable=False),
        sa.Column("tri_code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tri_code"),
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_state", sa.String(length=20), nullable=True),
        sa.Column("game_schedule_state", sa.String(length=10), nullable=True),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_score", sa.Integer(), nullable=True),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("home_team_score", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index(
        op.f("ix_games_away_team_id"), "games", ["away_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_games_home_team_id"), "games", ["home_team_id"], unique=False
    )
    op.create_index(op.f("ix_games_start_time"), "games", ["start_time"], unique=False)
    op.create_table(
        "goals",
        sa.Column("game_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("time_in_period", sa.String(length=5), nullable=False),
        sa.Column("time_remaining", sa.String(length=5), nullable=False),
        sa.Column("scoring_player_id", sa.Integer(), nullable=True),
        sa.Column("assist1_player_id", sa.Integer(), nullable=True),
        sa.Column("assist2_player_id", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("highlight_clip_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.game_id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "event_id"),
        sa.UniqueConstraint("highlight_clip_id"),
    )
    op.create_index(
        op.f("ix_goals_scoring_player_id"), "goals", ["scoring_player_id"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("team", sa.String(length=10), nullable=False),
        sa.Column(
            "posted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.game_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index(op.f("ix_posts_game_id"), "posts", ["game_id"], unique=False)
    op.create_index(op.f("ix_posts_posted"), "posts", ["posted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_posted"), table_name="posts")
    op.drop_index(op.f("ix_posts_game_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_goals_scoring_player_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_games_start_time"), table_name="games")
    op.drop_index(op.f("ix_games_home_team_id"), table_name="games")
    op.drop_index(op.f("ix_games_away_team_id"), table_name="games")
    op.drop_table("games")
    op.drop_table("teams")
    op.drop_index(op.f("ix_players_current_team_id"), table_name="players")
    op.drop_index(op.f("ix_players_current_team_abbrev"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
